var app = angular.module('app03');

app.directive('firstDirective', function() {
  return {
    template: "<div><div class='jumbotron'><p>This is generated by a Custom Directive</p><p>Tyring out</p></div><hr></div>",
    replace: true
  }
})